### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by smit1678** [openimagerynetwork/oin-register#4]
As discussed in the [OAM project meeting](https://docs.google.com/document/d/1ArKpugJNlJwxJS8rxUJlgndMYiFYLxsPpKTsKcT-Lac/edit), participation in OIN will include an agreement to a single license. 

CC-BY is on the table as the all inclusive, best open source license for an open imagery network: http://creativecommons.org/licenses/by/4.0/. 

If this looks good, then we'll include licensing language for CC-BY. Related to #3.

**Comment by lossyrob** [comment]
Have we worked out how the Attribution in CC-BY would work? Would we need to track and attribute individual committers, or would that license allow the attribution to only the Open Imagery Network?

**Comment by smathermather** [comment]
If memory serves, @cholmes and @wonderchook were advocating CC-BY would apply only OIN at the DC meeting.

**Comment by cholmes** [comment]
+1 on CC-BY 4.0.

The idea was that attribution would just go to 'contributors of Open Imagery Network', the same way OSM works. We won't track who all the providers all and try to show that.

I think there is a 'provider' field in the metadata, but from a licensing perspective that's just informative. We should work with someone (creative commons directly perhaps) to get the language right, but in general users of OIN should just need to attribute OIN. 

@smathermather - this is the OIN repo, so I think this discussion is just for OIN. OAM may include other things, but OIN is defined by the data license.

**Comment by wonderchook** [comment]
I think we would probably want to have something similar to the copyright page OSM has. Basically there are CC-BY sources listed there: http://www.openstreetmap.org/copyright This could really be something that is added to as a new node joins OIN.

**Comment by smathermather** [comment]
Ah, fair enough @cholmes. What I meant was what you said more clearly, i.e. 'contributors of Open Imagery Network' rather than tracking all providers individually.

**Comment by smit1678** [comment]
I like the idea of having a list of contributors. The first version of this is just the master list. 

Added license in https://github.com/openimagerynetwork/register/commit/9ccfa0ef53fe5b6a014344a86fec9b77b5e92a4d

Will close this out if nothing else to discuss here.
